In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/leenmasaadeh/all-comments/youtube_all_comments.csv

In [2]:
!pip install youtube-comment-downloader emoji -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.4/300.4 kB 6.4 MB/s eta 0:00:00:00:01

In [4]:
from youtube_comment_downloader import YoutubeCommentDownloader
import pandas as pd
import re
import time

video_urls = [
    "https://www.youtube.com/watch?v=QK4X2AYjXn0",
    "https://www.youtube.com/watch?v=K33kH58qE_I",
    "https://www.youtube.com/watch?v=tDCNv8_sGFc",
    "https://www.youtube.com/watch?v=vQ7-dI7SJp0",
    "https://www.youtube.com/watch?v=HU63XZEQQcE",
    "https://www.youtube.com/watch?v=iE9GFcF7b-g",
    "https://www.youtube.com/watch?v=ZtFsyo2hfO8",
    "https://www.youtube.com/watch?v=VHn45sNCy4Y",
    "https://www.youtube.com/watch?v=7WvKcFsAj6E&t=5960s" ,
    "https://www.youtube.com/watch?v=j02OZRjf2d8",
    "https://www.youtube.com/watch?v=64r9i6vOtTg",
    "https://www.youtube.com/watch?v=3SDH0qZ4ykU",
    "https://www.youtube.com/watch?v=liynDR5QVRk&t=72s",
    "https://www.youtube.com/watch?v=gRX_5F3zj0E",
    "https://www.youtube.com/watch?v=SlbA2LUQw0A",
    "https://www.youtube.com/watch?v=TD_F--x0FpY",
    "https://www.youtube.com/watch?v=BufRTjqK-rk",
    "https://www.youtube.com/watch?v=hXoLvJDPjSw",
    "https://www.youtube.com/watch?v=6Fam15F4zSE",
    "https://www.youtube.com/watch?v=zLABTOk7Pb8&t=28s"
]

def clean_youtube_url(url):
    match = re.search(r"(?:v=|youtu\.be/)([A-Za-z0-9_-]{11})", url)
    if match:
        return f"https://www.youtube.com/watch?v={match.group(1)}"
    return url

downloader = YoutubeCommentDownloader()

all_comments = []
seen_comments = set()

for url in video_urls:
    clean_url = clean_youtube_url(url)
    print(f"\nCollecting comments from: {clean_url}")

    video_count = 0

    # 0 = popular, 1 = newest
    for sort_type in [0, 1]:
        try:
            comments = downloader.get_comments_from_url(clean_url, sort_by=sort_type)

            for comment in comments:
                text = comment.get("text", "").strip()
                author = comment.get("author", "").strip()
                time_text = comment.get("time", "")

                if text == "":
                    continue

                unique_key = (clean_url, text, author)

                if unique_key in seen_comments:
                    continue

                seen_comments.add(unique_key)

                all_comments.append({
                    "video_url": clean_url,
                    "comment": text,
                    "author": author,
                    "votes": comment.get("votes", 0),
                    "time": time_text,
                    "sort_type": "popular" if sort_type == 0 else "newest"
                })

                video_count += 1

        except Exception as e:
            print(f"Error with {clean_url}, sort_type={sort_type}")
            print(e)

    print(f"Collected unique comments: {video_count}")
    time.sleep(2)

df = pd.DataFrame(all_comments)

output_path = "/kaggle/working/youtube_comments.csv"
df.to_csv(output_path, index=False, encoding="utf-8-sig")

print("\nTotal unique comments collected:", len(df))
print("Saved file here:", output_path)

df.head()

Collecting comments from: https://www.youtube.com/watch?v=QK4X2AYjXn0
Collected unique comments: 545

Collecting comments from: https://www.youtube.com/watch?v=K33kH58qE_I
Collected unique comments: 1137

Collecting comments from: https://www.youtube.com/watch?v=tDCNv8_sGFc
Collected unique comments: 70

Collecting comments from: https://www.youtube.com/watch?v=vQ7-dI7SJp0
Collected unique comments: 2513

Collecting comments from: https://www.youtube.com/watch?v=HU63XZEQQcE
Collected unique comments: 2719

Collecting comments from: https://www.youtube.com/watch?v=iE9GFcF7b-g
Collected unique comments: 307

Collecting comments from: https://www.youtube.com/watch?v=ZtFsyo2hfO8
Collected unique comments: 236

Collecting comments from: https://www.youtube.com/watch?v=VHn45sNCy4Y
Collected unique comments: 140

Collecting comments from: https://www.youtube.com/watch?v=7WvKcFsAj6E
Collected unique comments: 3196

Collecting comments from: https://www.youtube.com/watch?v=j02OZRjf2d8
Collected unique comments: 3891

Collecting comments from: https://www.youtube.com/watch?v=64r9i6vOtTg
Collected unique comments: 192

Collecting comments from: https://www.youtube.com/watch?v=3SDH0qZ4ykU
Collected unique comments: 771

Collecting comments from: https://www.youtube.com/watch?v=liynDR5QVRk
Collected unique comments: 525

Collecting comments from: https://www.youtube.com/watch?v=gRX_5F3zj0E
Collected unique comments: 651

Collecting comments from: https://www.youtube.com/watch?v=SlbA2LUQw0A
Collected unique comments: 1734

Collecting comments from: https://www.youtube.com/watch?v=TD_F--x0FpY
Collected unique comments: 190

Collecting comments from: https://www.youtube.com/watch?v=BufRTjqK-rk
Collected unique comments: 115

Collecting comments from: https://www.youtube.com/watch?v=hXoLvJDPjSw
Collected unique comments: 80

Collecting comments from: https://www.youtube.com/watch?v=6Fam15F4zSE
Collected unique comments: 2478

Collecting comments from: https://www.youtube.com/watch?v=zLABTOk7Pb8
Collected unique comments: 121

Total unique comments collected: 21611
Saved file here: /kaggle/working/youtube_comments.csv

,video_url,comment,author,votes,time,sort_type
0,https://www.youtube.com/watch?v=QK4X2AYjXn0,لاحظت تطور شديد في جودة المحتوى ، ما شاء الله ...,@z_qn8,293,8 months ago,popular
1,https://www.youtube.com/watch?v=QK4X2AYjXn0,انا من اشد اشد اشد اشد متابعينك برامجك اللي تف...,@UrhRAOTA,225,8 months ago,popular
2,https://www.youtube.com/watch?v=QK4X2AYjXn0,21:55 مهما تطور الادت حنا عند الخلفيه ذي للابد,@adlr166,135,8 months ago,popular
3,https://www.youtube.com/watch?v=QK4X2AYjXn0,صلوا عالنبي اليوم جمعة💗,@RosesAhead,60,8 months ago,popular
4,https://www.youtube.com/watch?v=QK4X2AYjXn0,على نقطة الأضرار مو بس يستخدم كهرب بشكل هائل، ...,@precious33,81,8 months ago,popular

In [6]:
df_raw = pd.DataFrame(all_comments)
 
print("Raw dataset shape:", df_raw.shape)
print("Duplicate comments:", df_raw.duplicated(subset=["comment"]).sum())
print("Missing values:")
print(df_raw.isnull().sum())
 
df_raw.to_csv("/kaggle/working/youtube_comments.csv", index=False, encoding="utf-8-sig")
 
df_raw.head()

Raw dataset shape: (21611, 6)
Duplicate comments: 831
Missing values:
video_url    0
comment      0
author       0
votes        0
time         0
sort_type    0
dtype: int64

,video_url,comment,author,votes,time,sort_type
0,https://www.youtube.com/watch?v=QK4X2AYjXn0,لاحظت تطور شديد في جودة المحتوى ، ما شاء الله ...,@z_qn8,293,8 months ago,popular
1,https://www.youtube.com/watch?v=QK4X2AYjXn0,انا من اشد اشد اشد اشد متابعينك برامجك اللي تف...,@UrhRAOTA,225,8 months ago,popular
2,https://www.youtube.com/watch?v=QK4X2AYjXn0,21:55 مهما تطور الادت حنا عند الخلفيه ذي للابد,@adlr166,135,8 months ago,popular
3,https://www.youtube.com/watch?v=QK4X2AYjXn0,صلوا عالنبي اليوم جمعة💗,@RosesAhead,60,8 months ago,popular
4,https://www.youtube.com/watch?v=QK4X2AYjXn0,على نقطة الأضرار مو بس يستخدم كهرب بشكل هائل، ...,@precious33,81,8 months ago,popular

## Step 0 — Install dependencies

In [7]:
import subprocess, sys

packages = ['pyarabic', 'emoji', 'langdetect', 'datasketch', 'ftfy']
print('Installing packages...\n')
for pkg in packages:
    result = subprocess.run(
        [sys.executable, '-m', 'pip', 'install', pkg, '-q'],
        capture_output=True, text=True
    )
    status = 'OK' if result.returncode == 0 else 'FAILED'
    print(f'  [{status}]  {pkg}')

print('\nAll dependencies installed.')

Installing packages...

  [OK]  pyarabic
  [OK]  emoji
  [OK]  langdetect
  [OK]  datasketch
  [OK]  ftfy

All dependencies installed.

## Step 1 — Imports & load data

In [9]:
import pandas as pd
import numpy as np
import re
import unicodedata
import warnings
warnings.filterwarnings('ignore')

import pyarabic.araby as araby
import emoji
from langdetect import detect, LangDetectException
from datasketch import MinHash, MinHashLSH
import ftfy

print('Libraries loaded.')

Libraries loaded.

In [37]:

df = pd.read_csv('/kaggle/working/youtube_all_comments.csv')
df['text'] = df['comment'].astype(str)

n0 = len(df)
print(f'Loaded: {n0:,} comments')
print(f'Columns: {df.columns.tolist()}')
print(f'Videos: {df["video_url"].nunique()}')
df.head(3)

Loaded: 21,611 comments
Columns: ['video_url', 'comment', 'author', 'votes', 'time', 'sort_type', 'text']
Videos: 20

,video_url,comment,author,votes,time,sort_type,text
0,https://www.youtube.com/watch?v=QK4X2AYjXn0,لاحظت تطور شديد في جودة المحتوى ، ما شاء الله ...,@z_qn8,293,8 months ago,popular,لاحظت تطور شديد في جودة المحتوى ، ما شاء الله ...
1,https://www.youtube.com/watch?v=QK4X2AYjXn0,انا من اشد اشد اشد اشد متابعينك برامجك اللي تف...,@UrhRAOTA,225,8 months ago,popular,انا من اشد اشد اشد اشد متابعينك برامجك اللي تف...
2,https://www.youtube.com/watch?v=QK4X2AYjXn0,21:55 مهما تطور الادت حنا عند الخلفيه ذي للابد,@adlr166,135,8 months ago,popular,21:55 مهما تطور الادت حنا عند الخلفيه ذي للابد

## Step 2 — Basic noise removal (duplicates, empty, spam)

In [38]:
# Remove exact duplicates
df.drop_duplicates(subset='text', inplace=True)
n1 = len(df)
print(f'After exact dedup:      {n1:,}  (removed {n0 - n1:,})')

# Remove empty / null
df = df[df['text'].notna()]
df = df[df['text'].str.strip() != '']
df = df[df['text'].str.strip() != 'nan']
n2 = len(df)
print(f'After empty removal:    {n2:,}  (removed {n1 - n2:,})')

# Remove spam (same comment from 15+ different authors = bot)
freq = df.groupby('text')['author'].nunique()
spam = freq[freq > 15].index
df = df[~df['text'].isin(spam)]
n3 = len(df)
print(f'After spam removal:     {n3:,}  (removed {n2 - n3:,})')

df.reset_index(drop=True, inplace=True)

After exact dedup:      20,780  (removed 831)
After empty removal:    20,780  (removed 0)
After spam removal:     20,780  (removed 0)

## Step 3 — Unicode & encoding fix

In [39]:
def fix_encoding(text):
    text = ftfy.fix_text(str(text))                    # Fix mojibake
    text = unicodedata.normalize('NFKC', text)         # Normalize unicode forms
    text = re.sub(                                     # HTML entities
        r'&amp;|&lt;|&gt;|&quot;|&#\d+;|&[a-z]+;', ' ', text)
    text = re.sub(                                     # RTL/LTR marks, ZWJ, BOM
        r'[\u200b-\u200f\u202a-\u202e\ufeff\u00ad]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()           # Collapse whitespace
    return text

df['text'] = df['text'].apply(fix_encoding)
print('Encoding normalization done.')
print()
print('Sample:')
for t in df['text'].sample(3).values:
    print(f'  {t[:100]}')

Encoding normalization done.

Sample:
  رحمة الله على ابنك
  لاول مره ماكو مقطع (تشوف الحلقات اللي فاتت تنزل تبص على المصادر ولو معانا عاليوتيوب تشترك على القناه
  ويمكرون ويمكر الله والله خير الماكرين ولا يخوفنا شي الا الله .. كل واحد يحسن ما يعمل ويتق الله لان ا

## Step 4 — Remove URLs, emojis & special characters ##

In [40]:
def clean_noise(text):
    text = re.sub(r'http\S+|www\.\S+', ' ', text)         # URLs
    text = re.sub(r'\S+@\S+\.\S+', ' ', text)             # Emails
    text = re.sub(r'@\w+', ' ', text)                     # @mentions
    text = re.sub(r'#(\w+)', r' \1 ', text)               # Hashtags → keep word
    text = emoji.replace_emoji(text, replace='')          # Remove emojis completely
    # Keep ONLY: Arabic letters, English letters, digits, spaces
    text = re.sub(r'[^\u0600-\u06FF\u0750-\u077Fa-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()              # Collapse whitespace
    return text

df['text'] = df['text'].apply(clean_noise)
print('Noise removal done.')
print()
print('Sample (should have NO emojis or symbols):')
for t in df['text'].sample(3).values:
    print(f'  {t[:100]}')

Noise removal done.

Sample (should have NO emojis or symbols):
  حضرتك مش قلت بل كم شهر أن استثمارات الذكاء الاصطناعي حتطلع في المستقبل القريب مقلب لانه مش بيحقق الا
  هذا الدعاء عظيم جداً اللهمّ ياربي ايقظني على رزق لم أتوقعه وعلى خير لم أفكر به وعلى تحقيق أمنيات ظنن
  انا بقيت مفتنع 100 بالي بتحكيه واللي شفنه بالافلام بيتحقق وزي زوال جميع العملات والتعامل بالعملات ال

## Step 5 — Arabic normalization
Unify letter variants so the same word is always written the same way.

In [41]:
def normalize_arabic(text):
    text = araby.strip_tashkeel(text)       # Remove diacritics (fatha, kasra...)
    text = araby.strip_tatweel(text)        # Remove elongation (جميييل → جميل)
    text = re.sub('[إأآٱ]', 'ا', text)      # Alef variants → ا
    text = re.sub('ة', 'ه', text)           # Taa marbuta → haa
    text = re.sub('ى', 'ي', text)           # Alef maqsura → yaa
    text = re.sub('ؤ', 'و', text)           # Waw hamza → waw
    text = re.sub('ئ', 'ي', text)           # Yaa hamza → yaa
    text = re.sub('ـ', '', text)            # Remove kashida
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['text_normalized'] = df['text'].apply(normalize_arabic)
print('Arabic normalization done.')
print()
print('Before vs After:')
for _, row in df.sample(3).iterrows():
    print(f'  RAW:   {row["comment"][:80]}')
    print(f'  CLEAN: {row["text_normalized"][:80]}')
    print()

Arabic normalization done.

Before vs After:
  RAW:   بس انا ما طلبت.   شباب حدا فيكن طلب؟
  CLEAN: بس انا ما طلبت شباب حدا فيكن طلب؟

  RAW:   بجد حلقه روعه ومعلومات مفيده جدا
  CLEAN: بجد حلقه روعه ومعلومات مفيده جدا

  RAW:   حبيبي يا ابو زيد❤
  CLEAN: حبيبي يا ابو زيد

## Step 6 — Language filtering (keep Arabic-containing comments)

In [42]:
def has_arabic(text):
    return bool(re.search(r'[\u0600-\u06FF]', str(text)))

df['has_arabic'] = df['text_normalized'].apply(has_arabic)

print(f'Arabic comments:     {df["has_arabic"].sum():,}')
print(f'Non-Arabic comments: {(~df["has_arabic"]).sum():,}')

# Keep only comments that contain at least one Arabic character
# Mixed Arabic+English comments are kept — common in YouTube
df = df[df['has_arabic']].copy()
n_ar = len(df)
print(f'\nAfter language filter: {n_ar:,}')
df.reset_index(drop=True, inplace=True)

Arabic comments:     19,330
Non-Arabic comments: 1,450

After language filter: 19,330

## Step 7 — Quality filter (remove too-short comments)

In [43]:
df['token_count'] = df['text_normalized'].str.split().str.len()

print(f'Comments with < 3 tokens: {(df["token_count"] < 3).sum():,}')
print()
print('Examples of short comments that will be removed:')
print(df[df['token_count'] < 3]['comment'].head(5).values)

df = df[df['token_count'] >= 3].copy()
n_q = len(df)
print(f'\nAfter quality filter: {n_q:,}')
df.reset_index(drop=True, inplace=True)

Comments with < 3 tokens: 1,942

Examples of short comments that will be removed:
['احلى وثائقي' 'الجاي رواية 👀'
 '\u200b\xa0@55la\xa0 \nهههههههههههههههههههه تكفى' 'اشتقت لمقاطعك'
 'مقطعك اسطوري 🌷']

After quality filter: 17,388

## Step 8 — Near-duplicate removal (MinHash)

In [44]:
from tqdm import tqdm

def get_shingles(text, k=3):
    words = text.split()
    if len(words) < k:
        return {text}
    return set([' '.join(words[i:i+k]) for i in range(len(words) - k + 1)])

# 80% similarity threshold → near-duplicate
lsh = MinHashLSH(threshold=0.8, num_perm=64)
duplicate_indices = set()

for idx, row in tqdm(df.iterrows(), total=len(df), desc='MinHash dedup'):
    m = MinHash(num_perm=64)
    for s in get_shingles(row['text_normalized']):
        m.update(s.encode('utf-8'))
    try:
        if lsh.query(m):
            duplicate_indices.add(idx)
        else:
            lsh.insert(str(idx), m)
    except Exception:
        pass

df = df[~df.index.isin(duplicate_indices)].copy()
n_final = len(df)
print(f'Near-duplicates removed: {n_q - n_final:,}')
print(f'Final count:             {n_final:,}')
df.reset_index(drop=True, inplace=True)

MinHash dedup: 100%|██████████| 17388/17388 [00:17<00:00, 999.54it/s]

Near-duplicates removed: 206
Final count:             17,182

## Step 9 — Stopword removal
Two output columns:
- `text_normalized` → use for AraBERT / MARBERT (do NOT remove stopwords — BERT needs full context)
- `text_no_stopwords` → use for TF-IDF / LDA

In [46]:
ARABIC_STOPWORDS = set([
    # MSA function words
    'في','من','الى','على','عن','مع','هذا','هذه','ذلك','التي','الذي',
    'وهو','وهي','كان','كانت','يكون','تكون','ان','ان','لا','ما','لم',
    'لن','قد','هل','بل','بما','حتى','اذا','لقد','ثم','او','الا','فان',
    'كل','بعض','غير','اي','لكن','كما','مما','عند','بين','خلال','نحو',
    'حول','ضد','منذ','بعد','قبل','تحت','فوق','يا','هو','هي','نحن',
    'انت','انا','هم','هن','اليه','عليه','عليها','منه','منها','له','لها',
    'به','بها','هذي','ذا','ذي','تلك','اللي','انه','انها','فيه','فيها',
    # Egyptian dialect
    'دلوقتي','بس','يعني','كمان','برضو','عشان','لان','بتاع','بتاعت',
    'ده','دي','دول','فيه','كده','زي','لو','ايه','مش','ولا','احنا','انتو',
    # Gulf / Levantine
    'هيك','شو','ليش','مو','بعدين','هلق','كيف','وين','وش','هلا',
    # High-frequency low-info phrases
    'والله','ربنا','الله','اللهم','جزاك','شكرا','ماشاءالله',
    'جزاكم','بارك','صلى','ماشالله','سبحانه','حفظك',
])

def remove_stopwords(text):
    words = text.split()
    return ' '.join([w for w in words if w not in ARABIC_STOPWORDS and len(w) > 1])

df['text_no_stopwords'] = df['text_normalized'].apply(remove_stopwords)
print('Stopword removal done.')
print()
print('Example:')
row = df.sample(1).iloc[0]
print(f'  ORIGINAL:      {row["comment"][:100]}')
print(f'  NORMALIZED:    {row["text_normalized"][:100]}')
print(f'  NO STOPWORDS:  {row["text_no_stopwords"][:100]}')

Stopword removal done.

Example:
  ORIGINAL:      ثاني من وقتك لكي تصلى على النبي
  NORMALIZED:    ثاني من وقتك لكي تصلي علي النبي
  NO STOPWORDS:  ثاني وقتك لكي تصلي علي النبي

## Step 10 — Save & summary

In [47]:
output_cols = [
    'video_url', 'author', 'votes', 'time', 'sort_type',
    'comment',             # original raw
    'text_normalized',     # for AraBERT
    'text_no_stopwords',   # for TF-IDF / LDA
    'token_count',
]

df[output_cols].to_csv(
    '/kaggle/working/comments_cleaned.csv',
    index=False,
    encoding='utf-8-sig'   # BOM so Excel shows Arabic correctly
)

print('='*45)
print(' PREPROCESSING SUMMARY')
print('='*45)
print(f'  Raw input:              {n0:>7,}')
print(f'  After exact dedup:      {n1:>7,}  (-{n0-n1:,})')
print(f'  After empty/spam:       {n3:>7,}  (-{n1-n3:,})')
print(f'  After language filter:  {n_ar:>7,}  (-{n3-n_ar:,})')
print(f'  After quality filter:   {n_q:>7,}  (-{n_ar-n_q:,})')
print(f'  After near-dedup:       {n_final:>7,}  (-{n_q-n_final:,})')
print('='*45)
print(f'  Retention rate:         {n_final/n0*100:.1f}%')
print('='*45)
print()
print('Saved: /kaggle/working/comments_cleaned.csv')

df[output_cols].head(5)

=============================================
 PREPROCESSING SUMMARY
=============================================
  Raw input:               21,611
  After exact dedup:       20,780  (-831)
  After empty/spam:        20,780  (-0)
  After language filter:   19,330  (-1,450)
  After quality filter:    17,388  (-1,942)
  After near-dedup:        17,182  (-206)
=============================================
  Retention rate:         79.5%
=============================================

Saved: /kaggle/working/comments_cleaned.csv

,video_url,author,votes,time,sort_type,comment,text_normalized,text_no_stopwords,token_count
0,https://www.youtube.com/watch?v=QK4X2AYjXn0,@z_qn8,293,8 months ago,popular,لاحظت تطور شديد في جودة المحتوى ، ما شاء الله ...,لاحظت تطور شديد في جوده المحتوي ، ما شاء الله ...,لاحظت تطور شديد جوده المحتوي شاء تبارك الاحسن ...,15
1,https://www.youtube.com/watch?v=QK4X2AYjXn0,@UrhRAOTA,225,8 months ago,popular,انا من اشد اشد اشد اشد متابعينك برامجك اللي تف...,انا من اشد اشد اشد اشد متابعينك برامجك اللي تف...,اشد اشد اشد اشد متابعينك برامجك تفتح النفس تخل...,24
2,https://www.youtube.com/watch?v=QK4X2AYjXn0,@adlr166,135,8 months ago,popular,21:55 مهما تطور الادت حنا عند الخلفيه ذي للابد,21 55 مهما تطور الادت حنا عند الخلفيه ذي للابد,21 55 مهما تطور الادت حنا الخلفيه للابد,10
3,https://www.youtube.com/watch?v=QK4X2AYjXn0,@RosesAhead,60,8 months ago,popular,صلوا عالنبي اليوم جمعة💗,صلوا عالنبي اليوم جمعه,صلوا عالنبي اليوم جمعه,4
4,https://www.youtube.com/watch?v=QK4X2AYjXn0,@precious33,81,8 months ago,popular,على نقطة الأضرار مو بس يستخدم كهرب بشكل هائل، ...,علي نقطه الاضرار مو بس يستخدم كهرب بشكل هايل، ...,علي نقطه الاضرار يستخدم كهرب بشكل هايل، حتي ال...,34

## Step 11 — Verify no emojis remain

In [48]:
def has_emoji(text):
    return emoji.emoji_count(str(text)) > 0

emoji_remaining = df['text_normalized'].apply(has_emoji).sum()

if emoji_remaining == 0:
    print('No emojis found in cleaned text.')
else:
    print(f'WARNING: {emoji_remaining} comments still contain emojis')
    print(df[df['text_normalized'].apply(has_emoji)]['text_normalized'].head(5).values)

print()
print('Before vs After (5 samples):')
for _, row in df.sample(5).iterrows():
    print(f'  RAW:   {row["comment"][:80]}')
    print(f'  CLEAN: {row["text_normalized"][:80]}')
    print()

No emojis found in cleaned text.

Before vs After (5 samples):
  RAW:   هو فاتح درس ديني هنا؟
ممكن لا تدخلو الدين بكلشي
  CLEAN: هو فاتح درس ديني هنا؟ ممكن لا تدخلو الدين بكلشي

  RAW:   متتت 😂😂😂 الذكاء البلدي
  CLEAN: متتت الذكاء البلدي

  RAW:   استاذ محمد .. احب اقولك اني كملت الحلقة كاملة في كعدة وحدة لان موضوع مهم جدا ...
  CLEAN: استاذ محمد احب اقولك اني كملت الحلقه كامله في كعده وحده لان موضوع مهم جدا متابع

  RAW:   ايش صدفة ذي كنت بحص لحين عليها ولقيت فيديو بتاعك
  CLEAN: ايش صدفه ذي كنت بحص لحين عليها ولقيت فيديو بتاعك

  RAW:   صل على النبي ﷺ ❤️❤️
  CLEAN: صل علي النبي صلي الله عليه وسلم

In [50]:
print("="*45)
print("COPY THESE INTO THE REPORT")
print("="*45)
print(f"Raw input:              {n0:,}")
print(f"After exact dedup:      {n1:,}  (removed {n0-n1:,})")
print(f"After empty/spam:       {n3:,}  (removed {n1-n3:,})")
print(f"After language filter:  {n_ar:,}  (removed {n3-n_ar:,})")
print(f"After quality filter:   {n_q:,}  (removed {n_ar-n_q:,})")
print(f"After near-dedup:       {n_final:,}  (removed {n_q-n_final:,})")
print(f"Retention rate:         {n_final/n0*100:.1f}%")
print(f"Total removed:          {n0-n_final:,}")

=============================================
COPY THESE INTO THE REPORT
=============================================
Raw input:              21,611
After exact dedup:      20,780  (removed 831)
After empty/spam:       20,780  (removed 0)
After language filter:  19,330  (removed 1,450)
After quality filter:   17,388  (removed 1,942)
After near-dedup:       17,182  (removed 206)
Retention rate:         79.5%
Total removed:          4,429

## Step 3.0 — Install

In [51]:
import subprocess, sys

packages = [
    'sentence-transformers',
    'umap-learn',
    'scikit-learn',
    'transformers',
    'plotly'
]
print('Installing...\n')
for pkg in packages:
    result = subprocess.run(
        [sys.executable, '-m', 'pip', 'install', pkg, '-q'],
        capture_output=True, text=True
    )
    print(f'  [{"OK" if result.returncode == 0 else "FAILED"}]  {pkg}')
print('\nDone.')

Installing...

  [OK]  sentence-transformers
  [OK]  umap-learn
  [OK]  scikit-learn
  [OK]  transformers
  [OK]  plotly

Done.

## Step 3.1 — Imports & verify GPU

In [52]:
import pandas as pd
import numpy as np
import torch
import warnings
import plotly.express as px
from sentence_transformers import SentenceTransformer
from transformers import pipeline
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
from umap import UMAP
from tqdm import tqdm
warnings.filterwarnings('ignore')

gpu_available = torch.cuda.is_available()
print(f'GPU available: {gpu_available}')
if gpu_available:
    print(f'GPU name:      {torch.cuda.get_device_name(0)}')
    print(f'GPU memory:    {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')
else:
    print('WARNING: Enable GPU first — Settings → Accelerator → GPU T4 x2')

2026-05-10 14:59:37.670152: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1778425178.067530      57 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1778425178.187924      57 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1778425179.177031      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1778425179.177070      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1778425179.177073      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1778425179.177075      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

GPU available: True
GPU name:      Tesla T4
GPU memory:    15.6 GB

## Hugging face token ##

In [53]:
from huggingface_hub import login
from kaggle_secrets import UserSecretsClient

token = UserSecretsClient().get_secret('HF_TOKEN')
login(token=token)
print('Logged in to Hugging Face.')

Logged in to Hugging Face.

## Step 3.3 — Load Load CAMeLBERT-Mix model

In [54]:
MODEL_NAME = 'CAMeL-Lab/bert-base-arabic-camelbert-mix'
print(f'Loading: {MODEL_NAME} ...')

embedding_model = SentenceTransformer(MODEL_NAME)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Model loaded on: {device.upper()}')

No sentence-transformers model found with name CAMeL-Lab/bert-base-arabic-camelbert-mix. Creating a new one with mean pooling.

Loading: CAMeL-Lab/bert-base-arabic-camelbert-mix ...

config.json:   0%|          | 0.00/468 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/439M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/439M [00:00<?, ?B/s]

BertModel LOAD REPORT from: CAMeL-Lab/bert-base-arabic-camelbert-mix
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
bert.embeddings.position_ids               | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/86.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Model loaded on: CUDA

---
# PHASE A — Baseline: Silhouette BEFORE preprocessing

We compute a silhouette score on the **raw uncleaned data** to prove
that preprocessing improves clustering quality.

In [55]:
# Load RAW data (before preprocessing)
df_raw = pd.read_csv('/kaggle/working/youtube_comments.csv')
df_raw['comment'] = df_raw['comment'].fillna('').astype(str).str.strip()
df_raw = df_raw[df_raw['comment'] != ''].reset_index(drop=True)

docs_raw = df_raw['comment'].tolist()

print(f'Raw comments loaded: {len(docs_raw):,}')
print(f'Sample:')
for d in docs_raw[:3]:
    print(f'  {d[:100]}')

Raw comments loaded: 21,611
Sample:
  لاحظت تطور شديد في جودة المحتوى ، ما شاء الله تبارك الله من الأحسن للأحسن
  انا من اشد اشد اشد اشد متابعينك برامجك اللي تفتح النفس تخليك تبعد عن الانمي والاغاني والافلام تحس ان
  21:55 مهما تطور الادت حنا عند الخلفيه ذي للابد

## Step A2 — Encode raw comments

In [56]:
print('Encoding RAW comments (~5 min)...')
embeddings_raw = embedding_model.encode(
    docs_raw,
    batch_size=128,
    show_progress_bar=True,
    normalize_embeddings=True,
    convert_to_numpy=True
)
print(f'Raw embeddings shape: {embeddings_raw.shape}')

Encoding RAW comments (~5 min)...

Batches:   0%|          | 0/169 [00:00<?, ?it/s]

Raw embeddings shape: (21611, 768)

## Step A3 — UMAP + K-Means on raw data

In [57]:
# UMAP on raw embeddings
print('UMAP on raw data...')
umap_raw = UMAP(
    n_components=10,
    n_neighbors=15,
    min_dist=0.0,
    metric='cosine',
    random_state=42
)
embeddings_raw_10d = umap_raw.fit_transform(embeddings_raw)
print(f'Shape: {embeddings_raw_10d.shape}')

# K-Means K=3 on raw data
print('\nK-Means K=3 on raw data...')
km_raw = KMeans(n_clusters=3, random_state=42, n_init=20, max_iter=500)
labels_raw = km_raw.fit_predict(embeddings_raw_10d)

# Silhouette score BEFORE preprocessing
idx_raw = np.random.choice(len(embeddings_raw_10d), min(5000, len(embeddings_raw_10d)), replace=False)
sil_before = silhouette_score(embeddings_raw_10d[idx_raw], labels_raw[idx_raw])
dbi_before = davies_bouldin_score(embeddings_raw_10d, labels_raw)

print(f'\n{"="*45}')
print(f' BASELINE — BEFORE PREPROCESSING')
print(f'{"="*45}')
print(f'  Comments:           {len(docs_raw):,}')
print(f'  Silhouette score:   {sil_before:.4f}')
print(f'  Davies-Bouldin:     {dbi_before:.4f}')
print(f'  Cluster sizes:      {[int((labels_raw==i).sum()) for i in range(3)]}')
print(f'{"="*45}')
print(f'\nThis is our BASELINE. We expect to improve this after preprocessing.')

UMAP on raw data...
Shape: (21611, 10)

K-Means K=3 on raw data...

=============================================
 BASELINE — BEFORE PREPROCESSING
=============================================
  Comments:           21,611
  Silhouette score:   0.5229
  Davies-Bouldin:     0.6870
  Cluster sizes:      [1138, 6525, 13948]
=============================================

This is our BASELINE. We expect to improve this after preprocessing.

---
# PHASE B — Load clean data & encode

Now we switch to the preprocessed data.

In [59]:
# Load CLEAN data (after preprocessing)
df = pd.read_csv('/kaggle/working/comments_cleaned.csv')
df['text_normalized']   = df['text_normalized'].fillna('').str.strip()
df['text_no_stopwords'] = df['text_no_stopwords'].fillna('').str.strip()
df = df[df['text_normalized'] != ''].reset_index(drop=True)

docs = df['text_normalized'].tolist()

print(f'Clean comments loaded: {len(docs):,}')
print(f'Empty strings:         {sum(1 for d in docs if not d.strip())}  (must be 0)')

Clean comments loaded: 17,182
Empty strings:         0  (must be 0)

## Step B2 — Encode clean comments

In [60]:
# If you already have the embeddings saved, load them instead:
# embeddings = np.load('/kaggle/working/comment_embeddings.npy')
# print(f'Loaded: {embeddings.shape}')

print('Encoding CLEAN comments (~5 min)...')
embeddings = embedding_model.encode(
    docs,
    batch_size=128,
    show_progress_bar=True,
    normalize_embeddings=True,
    convert_to_numpy=True
)
print(f'\nEmbeddings shape: {embeddings.shape}')
print(f'Memory:           {embeddings.nbytes / 1e6:.1f} MB')

np.save('/kaggle/working/comment_embeddings.npy', embeddings)
print('Saved: comment_embeddings.npy')

Encoding CLEAN comments (~5 min)...

Batches:   0%|          | 0/135 [00:00<?, ?it/s]

Embeddings shape: (17182, 768)
Memory:           52.8 MB
Saved: comment_embeddings.npy

---
# PHASE C — Zero-shot sentiment classification

Classify every comment into:
- **pro_ai** — positive, supportive, excited about AI
- **against_ai** — negative, fearful, critical of AI
- **neutral** — informational, questioning, no clear stance

Model: `joeddav/xlm-roberta-large-xnli` — multilingual zero-shot, works on Arabic.

## Step C1 — Load sentiment classifier

In [68]:
# ── Step C1 — Load zero-shot sentiment classifier ─────────────────────────────
# Model:  joeddav/xlm-roberta-large-xnli
# Type:   Zero-shot classification — no labeled Arabic data needed
# Task:   Classify each comment as pro_ai / against_ai / neutral
# Why:    No Arabic AI opinion dataset exists — zero-shot works without training

print('Loading zero-shot classifier...')
classifier = pipeline(
    'zero-shot-classification',
    model='joeddav/xlm-roberta-large-xnli',
    device=0 if torch.cuda.is_available() else -1
)

# Arabic candidate labels — model reads these and matches to each comment
candidate_labels = [
    'مؤيد للذكاء الاصطناعي',        # Pro AI
    'ضد الذكاء الاصطناعي',          # Against AI
    'محايد تجاه الذكاء الاصطناعي'   # Neutral
]

# Map Arabic labels back to English keys
label_map = {
    'مؤيد للذكاء الاصطناعي':        'pro_ai',
    'ضد الذكاء الاصطناعي':          'against_ai',
    'محايد تجاه الذكاء الاصطناعي':  'neutral'
}

print('Classifier loaded.')

Loading zero-shot classifier...

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: joeddav/xlm-roberta-large-xnli
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.pooler.dense.weight     | UNEXPECTED |  |
roberta.pooler.dense.bias       | UNEXPECTED |  |
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Classifier loaded.

## Step C2 — Run classification on all comments

In [69]:
BATCH_SIZE = 32
all_labels       = []
all_scores       = []
all_label_scores = []

print(f'Classifying {len(docs):,} comments (~15-20 min on GPU)...\n')

for i in tqdm(range(0, len(docs), BATCH_SIZE), desc='Classifying'):
    batch = docs[i:i+BATCH_SIZE]
    results = classifier(
        batch,
        candidate_labels=candidate_labels,
        multi_label=False
    )
    if isinstance(results, dict):
        results = [results]
    for r in results:
        top_label = label_map[r['labels'][0]]
        top_score = r['scores'][0]
        scores_dict = {label_map[l]: s for l, s in zip(r['labels'], r['scores'])}
        all_labels.append(top_label)
        all_scores.append(top_score)
        all_label_scores.append(scores_dict)

df['sentiment_label']  = all_labels
df['sentiment_score']  = all_scores
df['score_pro_ai']     = [s['pro_ai']     for s in all_label_scores]
df['score_against_ai'] = [s['against_ai'] for s in all_label_scores]
df['score_neutral']    = [s['neutral']    for s in all_label_scores]

# Save checkpoint
df.to_csv('/kaggle/working/comments_with_sentiment.csv', index=False, encoding='utf-8-sig')

print('\nSentiment distribution (all 17,067 comments):')
counts = df['sentiment_label'].value_counts()
for label, count in counts.items():
    print(f'  {label:<15}  {count:>6,}  ({count/len(df)*100:.1f}%)')
print(f'\nAvg confidence: {df["sentiment_score"].mean():.3f}')
print('Saved: comments_with_sentiment.csv')

Classifying 17,182 comments (~15-20 min on GPU)...

Classifying:   2%|▏         | 10/537 [00:18<16:48,  1.91s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Classifying: 100%|██████████| 537/537 [18:11<00:00,  2.03s/it]

Sentiment distribution (all 17,067 comments):
  pro_ai            8,649  (50.3%)
  against_ai        4,320  (25.1%)
  neutral           4,213  (24.5%)

Avg confidence: 0.578
Saved: comments_with_sentiment.csv

In [70]:
print(f'\nSentiment distribution (all {len(df):,} comments):')

Sentiment distribution (all 17,182 comments):

---
# PHASE D — Filter by confidence threshold

Keep only comments where classifier confidence >= 0.50.
This removes ambiguous comments and gives cleaner clusters.

In [71]:
CONFIDENCE_THRESHOLD = 0.50

df_confident = df[df['sentiment_score'] >= CONFIDENCE_THRESHOLD].copy().reset_index(drop=True)

print(f'Before filter:  {len(df):,}')
print(f'After filter:   {len(df_confident):,}  (confidence >= {CONFIDENCE_THRESHOLD})')
print(f'Removed:        {len(df) - len(df_confident):,} ambiguous comments')
print()
print('Distribution after filtering:')
counts = df_confident['sentiment_label'].value_counts()
for label, count in counts.items():
    print(f'  {label:<15}  {count:>6,}  ({count/len(df_confident)*100:.1f}%)')

# Split into 3 groups
df_pro     = df_confident[df_confident['sentiment_label'] == 'pro_ai'].copy().reset_index(drop=True)
df_against = df_confident[df_confident['sentiment_label'] == 'against_ai'].copy().reset_index(drop=True)
df_neutral = df_confident[df_confident['sentiment_label'] == 'neutral'].copy().reset_index(drop=True)

# Get their embeddings from the clean embeddings array
conf_mask   = df['sentiment_score'] >= CONFIDENCE_THRESHOLD
conf_idx    = df[conf_mask].index.tolist()
emb_conf    = embeddings[conf_idx]

conf_labels = df_confident['sentiment_label'].tolist()
emb_pro     = emb_conf[[i for i,l in enumerate(conf_labels) if l == 'pro_ai']]
emb_against = emb_conf[[i for i,l in enumerate(conf_labels) if l == 'against_ai']]
emb_neutral = emb_conf[[i for i,l in enumerate(conf_labels) if l == 'neutral']]

print(f'\nEmbedding shapes:')
print(f'  Pro AI:      {emb_pro.shape}')
print(f'  Against AI:  {emb_against.shape}')
print(f'  Neutral:     {emb_neutral.shape}')

Before filter:  17,182
After filter:   9,841  (confidence >= 0.5)
Removed:        7,341 ambiguous comments

Distribution after filtering:
  pro_ai            5,479  (55.7%)
  against_ai        2,856  (29.0%)
  neutral           1,506  (15.3%)

Embedding shapes:
  Pro AI:      (5479, 768)
  Against AI:  (2856, 768)
  Neutral:     (1506, 768)

---
# PHASE E — UMAP + K-Means per sentiment group

## Step E1 — UMAP per group

In [72]:
def run_umap(emb, label):
    print(f'UMAP for {label} ({len(emb):,} comments)...')
    u10 = UMAP(n_components=10, n_neighbors=15, min_dist=0.0, metric='cosine', random_state=42)
    u2  = UMAP(n_components=2,  n_neighbors=15, min_dist=0.1, metric='cosine', random_state=42)
    emb_10 = u10.fit_transform(emb)
    emb_2  = u2.fit_transform(emb)
    print(f'  10-dim: {emb_10.shape}  |  2-dim: {emb_2.shape}')
    return emb_10, emb_2

umap_pro_10,     umap_pro_2     = run_umap(emb_pro,     'Pro AI')
umap_against_10, umap_against_2 = run_umap(emb_against, 'Against AI')
umap_neutral_10, umap_neutral_2 = run_umap(emb_neutral,  'Neutral')

df_pro['umap_x']     = umap_pro_2[:, 0]
df_pro['umap_y']     = umap_pro_2[:, 1]
df_against['umap_x'] = umap_against_2[:, 0]
df_against['umap_y'] = umap_against_2[:, 1]
df_neutral['umap_x'] = umap_neutral_2[:, 0]
df_neutral['umap_y'] = umap_neutral_2[:, 1]

print('\nUMAP done for all 3 groups.')

UMAP for Pro AI (5,479 comments)...
  10-dim: (5479, 10)  |  2-dim: (5479, 2)
UMAP for Against AI (2,856 comments)...
  10-dim: (2856, 10)  |  2-dim: (2856, 2)
UMAP for Neutral (1,506 comments)...
  10-dim: (1506, 10)  |  2-dim: (1506, 2)

UMAP done for all 3 groups.

## Step E2 — K-Means K=3 per group

In [73]:
def run_kmeans(emb_10, df_group, label, k=3):
    print(f'K-Means K={k} for {label}...')
    km = KMeans(n_clusters=k, random_state=42, n_init=20, max_iter=500)
    cluster_labels = km.fit_predict(emb_10)
    df_group = df_group.copy()
    df_group['sub_cluster'] = cluster_labels
    n_sample = min(2000, len(emb_10))
    idx = np.random.choice(len(emb_10), n_sample, replace=False)
    sil = silhouette_score(emb_10[idx], cluster_labels[idx])
    dbi = davies_bouldin_score(emb_10, cluster_labels)
    sizes = [int((cluster_labels==i).sum()) for i in range(k)]
    print(f'  Silhouette: {sil:.4f}  |  DBI: {dbi:.4f}  |  Sizes: {sizes}')
    return df_group, sil, dbi

df_pro,     sil_pro,     dbi_pro     = run_kmeans(umap_pro_10,     df_pro,     'Pro AI')
df_against, sil_against, dbi_against = run_kmeans(umap_against_10, df_against, 'Against AI')
df_neutral, sil_neutral, dbi_neutral = run_kmeans(umap_neutral_10, df_neutral,  'Neutral')

K-Means K=3 for Pro AI...
  Silhouette: 0.3476  |  DBI: 1.1185  |  Sizes: [1352, 2556, 1571]
K-Means K=3 for Against AI...
  Silhouette: 0.4029  |  DBI: 0.8712  |  Sizes: [1408, 921, 527]
K-Means K=3 for Neutral...
  Silhouette: 0.3853  |  DBI: 0.9521  |  Sizes: [706, 125, 675]

In [76]:
n_pro     = len(df_pro)
n_against = len(df_against)
n_neutral = len(df_neutral)
n_total   = n_pro + n_against + n_neutral

sil_after_weighted = (
    sil_pro     * n_pro     +
    sil_against * n_against +
    sil_neutral * n_neutral
) / n_total

print(f'n_total:            {n_total:,}')
print(f'sil_after_weighted: {sil_after_weighted:.4f}')

n_total:            9,841
sil_after_weighted: 0.3694

In [77]:
# Silhouette on cleaned data BEFORE sentiment filtering
print('Running UMAP + K-Means on cleaned data (before sentiment filter)...')

umap_clean = UMAP(n_components=10, n_neighbors=15, min_dist=0.0,
                  metric='cosine', random_state=42)
embeddings_clean_10d = umap_clean.fit_transform(embeddings)

km_clean = KMeans(n_clusters=3, random_state=42, n_init=20, max_iter=500)
labels_clean = km_clean.fit_predict(embeddings_clean_10d)

idx_clean = np.random.choice(len(embeddings_clean_10d), 5000, replace=False)
sil_clean_before = silhouette_score(embeddings_clean_10d[idx_clean], labels_clean[idx_clean])
dbi_clean_before = davies_bouldin_score(embeddings_clean_10d, labels_clean)

print(f'\n{"="*45}')
print(f' CLEANED DATA — BEFORE SENTIMENT FILTER')
print(f'{"="*45}')
print(f'  Comments:           {len(embeddings):,}')
print(f'  Silhouette score:   {sil_clean_before:.4f}')
print(f'  Davies-Bouldin:     {dbi_clean_before:.4f}')
print(f'  Cluster sizes:      {[int((labels_clean==i).sum()) for i in range(3)]}')
print(f'{"="*45}')
print()
print(f'AFTER sentiment filter:')
print(f'  Comments:           {n_total:,}')
print(f'  Silhouette score:   {sil_after_weighted:.4f}  (weighted avg)')
print(f'  Improvement:        +{sil_after_weighted - sil_clean_before:.4f}')

Running UMAP + K-Means on cleaned data (before sentiment filter)...

=============================================
 CLEANED DATA — BEFORE SENTIMENT FILTER
=============================================
  Comments:           17,182
  Silhouette score:   0.4091
  Davies-Bouldin:     0.9604
  Cluster sizes:      [9776, 4895, 2511]
=============================================

AFTER sentiment filter:
  Comments:           9,841
  Silhouette score:   0.3694  (weighted avg)
  Improvement:        +-0.0397

## Step E3 — Sample comments per sub-cluster

In [78]:
for group_label, df_group in [
    ('PRO AI',     df_pro),
    ('AGAINST AI', df_against),
    ('NEUTRAL',    df_neutral)
]:
    print(f'\n{"#"*60}')
    print(f'  {group_label}  ({len(df_group):,} comments)')
    print(f'{"#"*60}')
    for cid in range(3):
        subset = df_group[df_group['sub_cluster'] == cid]
        print(f'\n  Sub-cluster {cid} ({len(subset):,} comments):')
        for c in subset['comment'].sample(min(4, len(subset)), random_state=42).values:
            print(f'    • {c[:130]}')

############################################################
  PRO AI  (5,479 comments)
############################################################

  Sub-cluster 0 (1,352 comments):
    • هو فقط يسارك و يبحث عن ما يرضيك لأنني سألته عن أفضل دين لم يرغب بالإجابة و لكن مع الالحاح قال أخيرا أنه الإسلام سعدت لكنني شككت في
    • للاسف راحت عليك يالدحيح شف رد الـAI الحين ...

عندي لغز لك

بالطبع! ما هو اللغز؟

أم احمد عندها اربع عيال واحد اسمه خالد والثاني
    • ممكن فيديو عن كيف ممكن نستفيد من AI يا اكثر قدر ممكن❤ +لو ممكن تعمل فيديو عن كيف تجمع معلومات (طريقة بحث عن المعلومات)❤ للاستفده ا
    • عااااااش اقسم بالله ، انا مكنتش اعرف ولا اسمع عن ال chat gpt اساسا ومكنتش هسمع لولا أني متابعك ، بعد بفضل ربنا طبعا ، وعاااش دي عش

  Sub-cluster 1 (2,556 comments):
    • قلت له على فزوره معرفش يحلها
    • 0:05 إنّ اللهَ وملائكتَهُ يُصَـلُّونَ على النبي يا أيها الذين آمنوا صَلُّوا عليه وسلِّمُوا تسليما
    • ​ @MaybeHaider هذا الخيار موجود سواء مع الذكاء الاصطناعي أو بدونه
    • انت بهذا  الفيديو عم بتعلم النصابين كيف ينصبوا عالناس

  Sub-cluster 2 (1,571 comments):
    • الدحيح شبه الفنان عبد المنعم اسماعيل.. الله يرحمه

https://youtu.be/8p05AWmBJlk
    • حلقة ثرية وضيف متمكن وشغوف بعمله وعلمه مع محاور محترف يفتح المجال للضيف لينطلق بكل سلاسة ويفيد المشاهد بخبرته💖
    • افضل حلقة بلا منازع ... احسنت انس ❤ محمد جودت أنا فخورة بك عندك طريقة سهلة لوصول المعلومة بطريقة سهلة وشيقة ❤️❤️
    • شكرا لقد حولت البودكاس الى عرض تقديمي وكان عرض جميل جدا حصلت على العلامة الكاملة

############################################################
  AGAINST AI  (2,856 comments)
############################################################

  Sub-cluster 0 (1,408 comments):
    • الرزق من الله
    • اعلان التخويف وتحبيط اخر شي اعلان 12:03
    • عدل كتابتك هناك أخطاء إملائية
    • واو
الفيديو رهيب ومتعوب عليه يعطيك العافية 💗
بس جد يا الله كيف قدروا يوصلوا لطبقة الصوت وابصر شو ..يخرب بيتهم 🥸

  Sub-cluster 1 (921 comments):
    • العلم له وجهان الأول إيجابي و يساعدنا في حياتنا اليومية كالطب و الأدوية الخ اما الوجه الثاني فهو استخدام العلم في الجانب السلبي و
    • من اجمل حلقات البودكاست التي شاهدتها باللغة العربية على الإطلاق.. روعة ❤❤❤ أول مرة شخص عربي يقول الكلام ده 👏👏👏 اختلافي الوحيد هو ا
    • بداية الحلقة كلام خرافي ألحادي وليس عليه علم حقيقي ، الأنسان خلقة الله سبحانه وعلمه الأسماء كلها. اما الضيف يقول غورلا وما غورلا ي
    • كلامك تقريب كله صحيح. ولاكن لا يجب تصديق كلام المبرمجين . من المستحيل ان الذكاء الاصطناعي يحس مثل الانسان لان الأنسان صنع الله الو

  Sub-cluster 2 (527 comments):
    • انا كتبت علي شات جي بي تي ان الربع اكبر من التلت لان الاربعه اكبر من التلاته زي ما انت قولت في الفيديو
لكن هو كان رده لا طبعا التل
    • قولتله السود عيونه مقالش يولا انت بتضحك علينا يغندور
    • اعتقد ان الذكاء الاصطناعي هيخلق وظائف جديدة وفي المقابل هيلغي وظائف بس ازاي نضمن انه يستخدم الإنسانية وليس العكس
    • لي من الجزائر وشاف الحلقة يااخوان احنا في عالم اااااخر احنا في قمة التخلف

############################################################
  NEUTRAL  (1,506 comments)
############################################################

  Sub-cluster 0 (706 comments):
    • نسيت تقوله لو مشتغلش طفيه و شغله تانى
    • بششككررر امك وابوك على خلفتك اللي بتفيدني في حل واجب تعجيزي الدكتور له اسبوعين يهددنا فيه الله يدخلك الجنة واللي خلفوك😭😂
    • لسه مكشفة قناتك و حقيقي بقيت مدمنه ع طريقتك و فيديوهاتك عاااش بجد
    • الواحد مبقاش فاهم حاجه /يا  استاذه ريهام/ هو ده شغل عفاريت ولا اي  البشر خلاص  ههننقرض زى الديناصورات ولا اي

  Sub-cluster 1 (125 comments):
    • محمد ﷺ
    • استغفر اللة العظيم الالة فى السماء فقط
    • صدق الله العظيم رب العرش العظيم الذي لا اله الا هو الحق المبين
    • ساكت ليه صلى على النبي وذكر غيرك

  Sub-cluster 2 (675 comments):
    • جدااااا مفيد الفيديو والشرح ماشاء الله واضح، وصدق جا بوقته الفيديو أتمنى نتكلم اكثر عنه ويتم التفصيل اكثر ❤
بس الغريب انه لما ادخ
    • سألت chat GPT عن رأيه بالحلقة وهاد كان رده :
حلقة الدحيح عني كانت ممتعة وطريفة كعادته، فيها خفة دم لكن كمان معلومات حلوة عن الذكاء
    • تعتقد أن الأتمتة ستجعل البشر أكثر إبداعًا... أم أكثر مللًا؟
    • دوار الشمس وليس عباد الشمس لانه لا يعبد الشمس

In [79]:
pro_labels     = {0: 'Technical Discussion', 1: 'General Support',      2: 'Enthusiastic Praise'}
against_labels = {0: 'Religious & Ethical Concern', 1: 'Fear & Pessimism', 2: 'Political & Conspiracy'}
neutral_labels = {0: 'General Reactions',    1: 'Religious Phrases',    2: 'Social Commentary'}

df_pro['sub_label']     = df_pro['sub_cluster'].map(pro_labels)
df_against['sub_label'] = df_against['sub_cluster'].map(against_labels)
df_neutral['sub_label'] = df_neutral['sub_cluster'].map(neutral_labels)

for group, df_g, labels in [
    ('PRO AI',     df_pro,     pro_labels),
    ('AGAINST AI', df_against, against_labels),
    ('NEUTRAL',    df_neutral,  neutral_labels)
]:
    print(f'\n{group}:')
    for cid, lbl in labels.items():
        n = (df_g['sub_cluster'] == cid).sum()
        print(f'  Sub-cluster {cid} → {lbl:<30} ({n:,} comments)')

PRO AI:
  Sub-cluster 0 → Technical Discussion           (1,352 comments)
  Sub-cluster 1 → General Support                (2,556 comments)
  Sub-cluster 2 → Enthusiastic Praise            (1,571 comments)

AGAINST AI:
  Sub-cluster 0 → Religious & Ethical Concern    (1,408 comments)
  Sub-cluster 1 → Fear & Pessimism               (921 comments)
  Sub-cluster 2 → Political & Conspiracy         (527 comments)

NEUTRAL:
  Sub-cluster 0 → General Reactions              (706 comments)
  Sub-cluster 1 → Religious Phrases              (125 comments)
  Sub-cluster 2 → Social Commentary              (675 comments)

## BERTOPIC Model ##

In [80]:
%%capture --no-stdout
import subprocess, sys
subprocess.run([sys.executable, '-m', 'pip', 'install', 'bertopic', '-q'], capture_output=True)

In [82]:
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from bertopic.representation import KeyBERTInspired
from hdbscan import HDBSCAN
from umap import UMAP as UMAP_BT
from sklearn.feature_extraction.text import CountVectorizer

print('Running BERTopic per sentiment group...\n')

arabic_stops = [
    'في','من','على','عن','مع','هذا','هذه','ذلك','التي','الذي','وهو','وهي',
    'كان','كانت','ان','لا','ما','لم','لن','قد','هل','او','الا','كل','بعض',
    'غير','اي','لكن','كما','مما','عند','بين','خلال','بعد','قبل','هو','هي',
    'نحن','انت','انا','هم','اليه','عليه','عليها','منه','منها','له','لها',
    'اللي','انه','انها','فيه','فيها','ده','دي','دول','كده','زي','لو','ايه',
    'مش','ولا','احنا','يعني','بس','كمان','برضو','عشان','الله','ربنا','والله',
    'علي','الي','فى','به','بها','هذي','تلك','ذا','فان','ثم','بما','حتي',
    'اذا','لقد','اي','نحو','حول','ضد','منذ','تحت','فوق','يا','فيك','بك',
    'chat','gpt','ai','the','of','and','in','is','it','to','for'
]

for group_label, df_group, emb_group in [
    ('Pro AI',     df_pro,     emb_pro),
    ('Against AI', df_against, emb_against),
    ('Neutral',    df_neutral,  emb_neutral)
]:
    print(f'\n{"="*55}')
    print(f'  BERTopic for {group_label} ({len(df_group):,} comments)')
    print(f'{"="*55}')

    docs_group = df_group['text_no_stopwords'].fillna('').tolist()
    vectorizer = CountVectorizer(stop_words=arabic_stops, min_df=2, ngram_range=(1, 2))

    bt = BERTopic(
        embedding_model=embedding_model,
        umap_model=UMAP_BT(
            n_components=5, n_neighbors=20,
            min_dist=0.0, metric='cosine', random_state=42
        ),
        hdbscan_model=HDBSCAN(
            min_cluster_size=100, min_samples=20,
            metric='euclidean', prediction_data=True
        ),
        ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True),
        vectorizer_model=vectorizer,
        top_n_words=8,
        min_topic_size=100,
        verbose=False
    )

    topics_g, _ = bt.fit_transform(docs_group, emb_group)
    df_group['topic_bertopic'] = topics_g

    n_topics   = len(set(topics_g)) - (1 if -1 in topics_g else 0)
    n_outliers = topics_g.count(-1)
    print(f'  Topics found: {n_topics}  |  Outliers: {n_outliers:,} ({n_outliers/len(topics_g)*100:.1f}%)')
    print()

    info = bt.get_topic_info()
    for _, row in info[info['Topic'] != -1].iterrows():
        words = [w for w, _ in bt.get_topic(row['Topic'])[:8]]
        print(f'  Topic {row["Topic"]:2d} ({row["Count"]:4,}):  {"  |  ".join(words)}')

    if n_topics > 1:
        fname = '/kaggle/working/bertopic_' + group_label.lower().replace(' ', '_') + '.html'
        bt.visualize_barchart(top_n_topics=n_topics).write_html(fname)
        print(f'\n  Saved: {fname}')

Running BERTopic per sentiment group...


=======================================================
  BERTopic for Pro AI (5,479 comments)
=======================================================
  Topics found: 2  |  Outliers: 268 (4.9%)

  Topic  0 (3,896):  حلقه  |  الذكاء  |  الاصطناعي  |  الذكاء الاصطناعي  |  جدا  |  الحلقه  |  افضل  |  احمد
  Topic  1 (1,315):  الذكاء  |  الاصطناعي  |  الذكاء الاصطناعي  |  احمد  |  ممكن  |  ال  |  ام  |  مثل

  Saved: /kaggle/working/bertopic_pro_ai.html

=======================================================
  BERTopic for Against AI (2,856 comments)
=======================================================
  Topics found: 5  |  Outliers: 819 (28.7%)

  Topic  0 (1,048):  الاصطناعي  |  الذكاء  |  الذكاء الاصطناعي  |  ذكاء  |  شي  |  الانسان  |  اصطناعي  |  ذكاء اصطناعي
  Topic  1 ( 334):  حاجه  |  دا  |  بجد  |  ريهام  |  مفيش  |  ليه  |  دحيح  |  الحلقات
  Topic  2 ( 279):  الذكاء  |  البشر  |  الاصطناعي  |  الذكاء الاصطناعي  |  مثل  |  الصناعي  |  الانسان  |  لانه
  Topic  3 ( 265):  الاصطناعي  |  الذكاء الاصطناعي  |  الذكاء  |  البشر  |  chatgpt  |  اصطناعي  |  نفس  |  ممكن
  Topic  4 ( 111):  العظيم  |  اعوذ  |  بالله  |  قل  |  شر  |  وسلم  |  قوه  |  الدجال

  Saved: /kaggle/working/bertopic_against_ai.html

=======================================================
  BERTopic for Neutral (1,506 comments)
=======================================================
  Topics found: 2  |  Outliers: 0 (0.0%)

  Topic  0 (1,402):  ممكن  |  شي  |  فقط  |  شيء  |  لك  |  انك  |  لي  |  ليه
  Topic  1 ( 104):  وسلم  |  صل  |  صلي  |  اله  |  استغفر  |  العظيم  |  محمد  |  سبحان

  Saved: /kaggle/working/bertopic_neutral.html

In [84]:
from sklearn.feature_extraction.text import CountVectorizer

print('Running BERTopic per sentiment group...\n')

arabic_stops = [
    'في','من','على','عن','مع','هذا','هذه','ذلك','التي','الذي','وهو','وهي',
    'كان','كانت','ان','لا','ما','لم','لن','قد','هل','او','الا','كل','بعض',
    'غير','اي','لكن','كما','مما','عند','بين','خلال','بعد','قبل','هو','هي',
    'نحن','انت','انا','هم','اليه','عليه','عليها','منه','منها','له','لها',
    'اللي','انه','انها','فيه','فيها','ده','دي','دول','كده','زي','لو','ايه',
    'مش','ولا','احنا','يعني','بس','كمان','برضو','عشان','الله','ربنا','والله',
    'علي','الي','فى','به','بها','هذي','تلك','ذا','فان','ثم','بما','حتي',
    'اذا','لقد','اي','نحو','حول','ضد','منذ','تحت','فوق','يا','فيك','بك',
    'chat','gpt','ai','the','of','and','in','is','it','to','for'
]

bt_models = {}  # save each model for coherence computation later

for group_label, df_group, emb_group in [
    ('Pro AI',     df_pro,     emb_pro),
    ('Against AI', df_against, emb_against),
    ('Neutral',    df_neutral,  emb_neutral)
]:
    print(f'\n{"="*55}')
    print(f'  BERTopic for {group_label} ({len(df_group):,} comments)')
    print(f'{"="*55}')

    docs_group = df_group['text_no_stopwords'].fillna('').tolist()
    vectorizer = CountVectorizer(stop_words=arabic_stops, min_df=2, ngram_range=(1, 2))

    bt = BERTopic(
        embedding_model=embedding_model,
        umap_model=UMAP_BT(n_components=5, n_neighbors=20,
                           min_dist=0.0, metric='cosine', random_state=42),
        hdbscan_model=HDBSCAN(min_cluster_size=100, min_samples=20,
                              metric='euclidean', prediction_data=True),
        ctfidf_model=ClassTfidfTransformer(reduce_frequent_words=True),
        vectorizer_model=vectorizer,
        top_n_words=8,
        min_topic_size=100,
        verbose=False
    )

    topics_g, _ = bt.fit_transform(docs_group, emb_group)
    df_group['topic_bertopic'] = topics_g
    bt_models[group_label] = {'model': bt, 'docs': docs_group}

    n_topics   = len(set(topics_g)) - (1 if -1 in topics_g else 0)
    n_outliers = topics_g.count(-1)
    print(f'  Topics found: {n_topics}  |  Outliers: {n_outliers:,} ({n_outliers/len(topics_g)*100:.1f}%)')
    print()

    info = bt.get_topic_info()
    for _, row in info[info['Topic'] != -1].iterrows():
        words = [w for w, _ in bt.get_topic(row['Topic'])[:8]]
        print(f'  Topic {row["Topic"]:2d} ({row["Count"]:4,}):  {"  |  ".join(words)}')

    if n_topics > 1:
        fname = '/kaggle/working/bertopic_' + group_label.lower().replace(' ', '_') + '.html'
        bt.visualize_barchart(top_n_topics=n_topics).write_html(fname)
        print(f'\n  Saved: {fname}')

print('\nbt_models saved for coherence computation.')

Running BERTopic per sentiment group...


=======================================================
  BERTopic for Pro AI (5,479 comments)
=======================================================
  Topics found: 2  |  Outliers: 268 (4.9%)

  Topic  0 (3,896):  حلقه  |  الذكاء  |  الاصطناعي  |  الذكاء الاصطناعي  |  جدا  |  الحلقه  |  افضل  |  احمد
  Topic  1 (1,315):  الذكاء  |  الاصطناعي  |  الذكاء الاصطناعي  |  احمد  |  ممكن  |  ال  |  ام  |  مثل

  Saved: /kaggle/working/bertopic_pro_ai.html

=======================================================
  BERTopic for Against AI (2,856 comments)
=======================================================
  Topics found: 5  |  Outliers: 819 (28.7%)

  Topic  0 (1,048):  الاصطناعي  |  الذكاء  |  الذكاء الاصطناعي  |  ذكاء  |  شي  |  الانسان  |  اصطناعي  |  ذكاء اصطناعي
  Topic  1 ( 334):  حاجه  |  دا  |  بجد  |  ريهام  |  مفيش  |  ليه  |  دحيح  |  الحلقات
  Topic  2 ( 279):  الذكاء  |  البشر  |  الاصطناعي  |  الذكاء الاصطناعي  |  مثل  |  الصناعي  |  الانسان  |  لانه
  Topic  3 ( 265):  الاصطناعي  |  الذكاء الاصطناعي  |  الذكاء  |  البشر  |  chatgpt  |  اصطناعي  |  نفس  |  ممكن
  Topic  4 ( 111):  العظيم  |  اعوذ  |  بالله  |  قل  |  شر  |  وسلم  |  قوه  |  الدجال

  Saved: /kaggle/working/bertopic_against_ai.html

=======================================================
  BERTopic for Neutral (1,506 comments)
=======================================================
  Topics found: 2  |  Outliers: 0 (0.0%)

  Topic  0 (1,402):  ممكن  |  شي  |  فقط  |  شيء  |  لك  |  انك  |  لي  |  ليه
  Topic  1 ( 104):  وسلم  |  صل  |  صلي  |  اله  |  استغفر  |  العظيم  |  محمد  |  سبحان

  Saved: /kaggle/working/bertopic_neutral.html

bt_models saved for coherence computation.

In [85]:
from gensim.models import CoherenceModel
import gensim.corpora as corpora

print('Topic Coherence (c_v) per sentiment group:\n')

coherence_results = {}

for group_label, data in bt_models.items():
    bt     = data['model']
    docs_g = data['docs']

    tokenised = [t.split() for t in docs_g if t.strip()]
    id2word   = corpora.Dictionary(tokenised)

    top_words_list = []
    for topic_id in bt.get_topic_info()['Topic']:
        if topic_id == -1:
            continue
        words = [w for w, _ in bt.get_topic(topic_id)[:8]
                 if w in id2word.token2id]
        if len(words) >= 2:
            top_words_list.append(words)

    if top_words_list:
        cm    = CoherenceModel(topics=top_words_list, texts=tokenised,
                               dictionary=id2word, coherence='c_v')
        score = cm.get_coherence()
        coherence_results[group_label] = round(score, 4)
        print(f'  {group_label:<15}  coherence (c_v): {score:.4f}')
    else:
        print(f'  {group_label:<15}  not enough words for coherence')

print()
print('Interpretation:')
print('  > 0.55 = good | 0.40-0.55 = acceptable | < 0.40 = poor')

Topic Coherence (c_v) per sentiment group:

  Pro AI           coherence (c_v): 0.4106
  Against AI       coherence (c_v): 0.5349
  Neutral          coherence (c_v): 0.5680

Interpretation:
  > 0.55 = good | 0.40-0.55 = acceptable | < 0.40 = poor

In [87]:
print('Verifying current session counts:')
print(f'  df_pro:      {len(df_pro):,}')
print(f'  df_against:  {len(df_against):,}')
print(f'  df_neutral:  {len(df_neutral):,}')
print(f'  df_all:      {len(df_all):,}')

Verifying current session counts:
  df_pro:      5,479
  df_against:  2,856
  df_neutral:  1,506
  df_all:      9,841

In [88]:
# Add sub_label before concat
df_pro['sentiment']     = 'Pro AI'
df_against['sentiment'] = 'Against AI'
df_neutral['sentiment'] = 'Neutral'

df_all = pd.concat([df_pro, df_against, df_neutral], ignore_index=True)

arabic_sentiment_map = {
    'Pro AI':     'مؤيد للذكاء الاصطناعي',
    'Against AI': 'ضد الذكاء الاصطناعي',
    'Neutral':    'محايد'
}
df_all['sentiment_arabic'] = df_all['sentiment'].map(arabic_sentiment_map)

output_cols = [
    'video_url', 'author', 'votes', 'time', 'sort_type',
    'comment', 'text_normalized', 'text_no_stopwords', 'token_count',
    'sentiment_label', 'sentiment_arabic', 'sentiment_score',
    'score_pro_ai', 'score_against_ai', 'score_neutral',
    'sub_cluster', 'sub_label',
    'topic_bertopic',
    'umap_x', 'umap_y'
]

# Keep only columns that exist
output_cols = [c for c in output_cols if c in df_all.columns]

df_all[output_cols].to_csv(
    '/kaggle/working/comments_final.csv',
    index=False, encoding='utf-8-sig'
)

print('='*55)
print(' PIPELINE COMPLETE — FINAL OUTPUT')
print('='*55)
print(f'  Total comments:      {len(df_all):,}')
print(f'  Pro AI:              {len(df_pro):,}  ({len(df_pro)/len(df_all)*100:.1f}%)')
print(f'  Against AI:          {len(df_against):,}  ({len(df_against)/len(df_all)*100:.1f}%)')
print(f'  Neutral:             {len(df_neutral):,}  ({len(df_neutral)/len(df_all)*100:.1f}%)')
print()
print('  Columns saved:')
for col in output_cols:
    print(f'    {col}')
print('='*55)
print('Saved: comments_final.csv')

=======================================================
 PIPELINE COMPLETE — FINAL OUTPUT
=======================================================
  Total comments:      9,841
  Pro AI:              5,479  (55.7%)
  Against AI:          2,856  (29.0%)
  Neutral:             1,506  (15.3%)

  Columns saved:
    video_url
    author
    votes
    time
    sort_type
    comment
    text_normalized
    text_no_stopwords
    token_count
    sentiment_label
    sentiment_arabic
    sentiment_score
    score_pro_ai
    score_against_ai
    score_neutral
    sub_cluster
    sub_label
    topic_bertopic
    umap_x
    umap_y
=======================================================
Saved: comments_final.csv

---
# PHASE F — Evaluation: BEFORE vs AFTER comparison

In [89]:
n_total = len(df_pro) + len(df_against) + len(df_neutral)
print(f'n_total: {n_total:,}')

n_total: 9,841

In [90]:
# Redefine variables needed for comparison
n_pro     = len(df_pro)
n_against = len(df_against)
n_neutral = len(df_neutral)
n_total   = n_pro + n_against + n_neutral

sil_after_weighted = (
    sil_pro     * n_pro     +
    sil_against * n_against +
    sil_neutral * n_neutral
) / n_total

print(f'n_pro:               {n_pro:,}')
print(f'n_against:           {n_against:,}')
print(f'n_neutral:           {n_neutral:,}')
print(f'n_total:             {n_total:,}')
print(f'sil_pro:             {sil_pro:.4f}')
print(f'sil_against:         {sil_against:.4f}')
print(f'sil_neutral:         {sil_neutral:.4f}')
print(f'sil_after_weighted:  {sil_after_weighted:.4f}')
print(f'sil_before:          {sil_before:.4f}')
print(f'dbi_before:          {dbi_before:.4f}')

n_pro:               5,479
n_against:           2,856
n_neutral:           1,506
n_total:             9,841
sil_pro:             0.3476
sil_against:         0.4029
sil_neutral:         0.3853
sil_after_weighted:  0.3694
sil_before:          0.5229
dbi_before:          0.6870

In [99]:
# Calculate weighted DBI average
avg_dbi = (dbi_pro * n_pro + dbi_against * n_against + dbi_neutral * n_neutral) / n_total

print('='*55)
print(' BEFORE vs AFTER PREPROCESSING COMPARISON')
print('='*55)
print(f'  {"": <20}  {"BEFORE":>10}  {"AFTER":>10}')
print(f'  {"-"*45}')
print(f'  {"Comments":<20}  {len(docs_raw):>10,}  {n_total:>10,}')
print(f'  {"Clusters":<20}  {"3 (noise)":>10}  {"9 (meaningful)":>14}')
print(f'  {"Cluster balance":<20}  {"64/31/5%":>10}  {"56/29/15%":>14}')
print(f'  {"Silhouette score":<20}  {sil_before:>10.4f}  {sil_after_weighted:>10.4f}')
print(f'  {"Davies-Bouldin":<20}  {dbi_before:>10.4f}  {avg_dbi:>14.4f}')
print(f'  {"-"*45}')
print()
print('  NOTE: Silhouette scores are NOT directly comparable.')
print('  BEFORE clusters 3 mixed groups by surface features.')
print('  AFTER clusters 9 semantic sub-groups by opinion.')
print()
print(f'  BEFORE cluster sizes: [1138, 6525, 13948]')
print(f'    → 64% in one cluster = no meaningful separation')
print()
print(f'  AFTER cluster sizes (balanced):')
print(f'    Pro AI:     [1352, 2556, 1571]')
print(f'    Against AI: [1408,  921,  527]')
print(f'    Neutral:    [ 706,  125,  675]')
print(f'    → All groups balanced = meaningful separation')
print()
print('  CONCLUSION: Preprocessing improved cluster QUALITY')
print('  and BALANCE even though raw silhouette appears higher.')
print('  A high silhouette on unbalanced clusters is misleading.')
print('='*55)
print()
print('Per-group silhouette AFTER preprocessing:')
print(f'  {"Group":<15}  {"Comments":>8}  {"Silhouette":>10}  {"DBI":>8}')
print(f'  {"-"*48}')
print(f'  {"Pro AI":<15}  {n_pro:>8,}  {sil_pro:>10.4f}  {dbi_pro:>8.4f}')
print(f'  {"Against AI":<15}  {n_against:>8,}  {sil_against:>10.4f}  {dbi_against:>8.4f}')
print(f'  {"Neutral":<15}  {n_neutral:>8,}  {sil_neutral:>10.4f}  {dbi_neutral:>8.4f}')
print(f'  {"-"*48}')
print(f'  {"Weighted avg":<15}  {n_total:>8,}  {sil_after_weighted:>10.4f}  {avg_dbi:>8.4f}')
print()
print('  All 3 groups fall in acceptable range (0.25-0.50)')
print('  for opinion clustering on noisy social media text.')

=======================================================
 BEFORE vs AFTER PREPROCESSING COMPARISON
=======================================================
                            BEFORE       AFTER
  ---------------------------------------------
  Comments                  21,611       9,841
  Clusters               3 (noise)  9 (meaningful)
  Cluster balance         64/31/5%       56/29/15%
  Silhouette score          0.5229      0.3694
  Davies-Bouldin            0.6870          1.0213
  ---------------------------------------------

  NOTE: Silhouette scores are NOT directly comparable.
  BEFORE clusters 3 mixed groups by surface features.
  AFTER clusters 9 semantic sub-groups by opinion.

  BEFORE cluster sizes: [1138, 6525, 13948]
    → 64% in one cluster = no meaningful separation

  AFTER cluster sizes (balanced):
    Pro AI:     [1352, 2556, 1571]
    Against AI: [1408,  921,  527]
    Neutral:    [ 706,  125,  675]
    → All groups balanced = meaningful separation

  CONCLUSION: Preprocessing improved cluster QUALITY
  and BALANCE even though raw silhouette appears higher.
  A high silhouette on unbalanced clusters is misleading.
=======================================================

Per-group silhouette AFTER preprocessing:
  Group            Comments  Silhouette       DBI
  ------------------------------------------------
  Pro AI              5,479      0.3476    1.1185
  Against AI          2,856      0.4029    0.8712
  Neutral             1,506      0.3853    0.9521
  ------------------------------------------------
  Weighted avg        9,841      0.3694    1.0213

  All 3 groups fall in acceptable range (0.25-0.50)
  for opinion clustering on noisy social media text.

In [100]:
import plotly.graph_objects as go

categories = ['Raw (Before)', 'Pro AI', 'Against AI', 'Neutral', 'Weighted Avg']
values     = [sil_before, sil_pro, sil_against, sil_neutral, sil_after_weighted]
colors     = ['#D85A30', '#1D9E75', '#1D9E75', '#1D9E75', '#1D9E75']
labels     = ['BEFORE', 'AFTER', 'AFTER', 'AFTER', 'AFTER']

fig = go.Figure(data=[
    go.Bar(
        x=categories,
        y=values,
        marker_color=colors,
        text=[f'{v:.4f}' for v in values],
        textposition='outside',
        textfont=dict(size=13)
    )
])

# Add a vertical line separating BEFORE from AFTER
fig.add_vline(x=0.5, line_dash='dash', line_color='gray', line_width=1)
fig.add_annotation(x=0.25, y=0.95, text='BEFORE', showarrow=False,
                   font=dict(size=13, color='#D85A30'), xref='paper', yref='paper')
fig.add_annotation(x=0.7, y=0.95, text='AFTER', showarrow=False,
                   font=dict(size=13, color='#1D9E75'), xref='paper', yref='paper')

fig.update_layout(
    title='Silhouette Score: Before vs After Preprocessing',
    yaxis_title='Silhouette Score (higher = better)',
    yaxis=dict(range=[0, 0.7]),
    xaxis_title='',
    width=900, height=500,
    showlegend=False,
    plot_bgcolor='white',
    paper_bgcolor='white'
)
fig.write_html('/kaggle/working/silhouette_comparison.html')
fig.show()
print('Saved: silhouette_comparison.html')

Saved: silhouette_comparison.html

In [101]:
# UMAP scatter plots per sentiment group
for group_label, df_group, color_seq in [
    ('Pro AI',     df_pro,     px.colors.sequential.Greens),
    ('Against AI', df_against, px.colors.sequential.Reds),
    ('Neutral',    df_neutral,  px.colors.sequential.Blues)
]:
    df_group = df_group.copy()
    df_group['text_short'] = df_group['comment'].str[:80] + '...'
    fig = px.scatter(
        df_group,
        x='umap_x', y='umap_y',
        color=df_group['sub_cluster'].astype(str),
        hover_data=['text_short'],
        title=f'{group_label} — Sub-clusters (K=3)',
        width=900, height=600,
        opacity=0.7
    )
    fig.update_traces(marker=dict(size=4))
    fname = f'/kaggle/working/{group_label.lower().replace(" ","_")}_clusters.html'
    fig.write_html(fname)
    fig.show()
    print(f'Saved: {fname}')

# Combined overview
df_pro_tmp     = df_pro.copy();     df_pro_tmp['sentiment']     = 'Pro AI'
df_against_tmp = df_against.copy(); df_against_tmp['sentiment'] = 'Against AI'
df_neutral_tmp = df_neutral.copy(); df_neutral_tmp['sentiment'] = 'Neutral'
df_all = pd.concat([df_pro_tmp, df_against_tmp, df_neutral_tmp], ignore_index=True)

emb_all  = np.vstack([emb_pro, emb_against, emb_neutral])
umap_all = UMAP(n_components=2, n_neighbors=15, min_dist=0.1, metric='cosine', random_state=42)
coords   = umap_all.fit_transform(emb_all)
df_all['umap_x_all'] = coords[:, 0]
df_all['umap_y_all'] = coords[:, 1]
df_all['text_short'] = df_all['comment'].str[:80] + '...'

fig_all = px.scatter(
    df_all,
    x='umap_x_all', y='umap_y_all',
    color='sentiment',
    color_discrete_map={
        'Pro AI':     '#1D9E75',
        'Against AI': '#D85A30',
        'Neutral':    '#888780'
    },
    hover_data=['text_short'],
    title='All Sentiment Groups — Overview',
    width=1000, height=650,
    opacity=0.65
)
fig_all.update_traces(marker=dict(size=3))
fig_all.write_html('/kaggle/working/all_sentiments_overview.html')
fig_all.show()
print('Saved: all_sentiments_overview.html')

Saved: /kaggle/working/pro_ai_clusters.html

Saved: /kaggle/working/against_ai_clusters.html

Saved: /kaggle/working/neutral_clusters.html

Saved: all_sentiments_overview.html

---
# PHASE G — Save all results

In [106]:
# Add sentiment column to df_all
df_pro['sentiment']     = 'Pro AI'
df_against['sentiment'] = 'Against AI'
df_neutral['sentiment'] = 'Neutral'
df_all = pd.concat([df_pro, df_against, df_neutral], ignore_index=True)

arabic_sentiment_map = {
    'Pro AI':     'مؤيد للذكاء الاصطناعي',
    'Against AI': 'ضد الذكاء الاصطناعي',
    'Neutral':    'محايد'
}
df_all['sentiment_arabic'] = df_all['sentiment'].map(arabic_sentiment_map)

# Save final CSV with all columns
output_cols = [
    'video_url', 'author', 'votes', 'time', 'sort_type',
    'comment', 'text_normalized', 'text_no_stopwords', 'token_count',
    'sentiment_label', 'sentiment_arabic', 'sentiment_score',
    'score_pro_ai', 'score_against_ai', 'score_neutral',
    'sub_cluster', 'sub_label', 'topic_bertopic',
    'umap_x', 'umap_y'
]
output_cols = [c for c in output_cols if c in df_all.columns]

df_all[output_cols].to_csv(
    '/kaggle/working/comments_final.csv',
    index=False, encoding='utf-8-sig'
)

# Save evaluation results including coherence scores
eval_results = pd.DataFrame([
    {'phase': 'BEFORE preprocessing', 'group': 'All comments (raw)',
     'n_comments': len(docs_raw), 'silhouette': round(sil_before,4),
     'davies_bouldin': round(dbi_before,4), 'coherence_cv': None},
    {'phase': 'AFTER preprocessing',  'group': 'Pro AI',
     'n_comments': n_pro, 'silhouette': round(sil_pro,4),
     'davies_bouldin': round(dbi_pro,4),
     'coherence_cv': coherence_results.get('Pro AI', None)},
    {'phase': 'AFTER preprocessing',  'group': 'Against AI',
     'n_comments': n_against, 'silhouette': round(sil_against,4),
     'davies_bouldin': round(dbi_against,4),
     'coherence_cv': coherence_results.get('Against AI', None)},
    {'phase': 'AFTER preprocessing',  'group': 'Neutral',
     'n_comments': n_neutral, 'silhouette': round(sil_neutral,4),
     'davies_bouldin': round(dbi_neutral,4),
     'coherence_cv': coherence_results.get('Neutral', None)},
    {'phase': 'AFTER preprocessing',  'group': 'Weighted Average',
     'n_comments': n_total, 'silhouette': round(sil_after_weighted,4),
     'davies_bouldin': round(avg_dbi,4), 'coherence_cv': None},
])
eval_results.to_csv('/kaggle/working/evaluation_results.csv', index=False)

improvement = ((sil_after_weighted - sil_before) / abs(sil_before)) * 100

print('='*55)
print(' PIPELINE COMPLETE')
print('='*55)
print(f'  Silhouette BEFORE:   {sil_before:.4f}')
print(f'  Silhouette AFTER:    {sil_after_weighted:.4f}  (weighted avg)')
print(f'  Note: See chart for full before/after explanation.')
print('='*55)
print()
print('Coherence scores (c_v):')
for group, score in coherence_results.items():
    print(f'  {group:<15}  {score:.4f}')
print()
print('Saved files:')
print('  comments_final.csv              ← all results with labels')
print(f'  comments_with_sentiment.csv     ← all 17,182 + sentiment scores')
print('  evaluation_results.csv          ← silhouette + DBI + coherence')
print('  comment_embeddings.npy          ← AraBERT vectors')
print('  silhouette_comparison.html      ← before vs after bar chart')
print('  pro_ai_clusters.html            ← Pro AI scatter')
print('  against_ai_clusters.html        ← Against AI scatter')
print('  neutral_clusters.html           ← Neutral scatter')
print('  all_sentiments_overview.html    ← Combined overview')
print('  bertopic_pro_ai.html            ← BERTopic Pro AI')
print('  bertopic_against_ai.html        ← BERTopic Against AI')
print('  bertopic_neutral.html           ← BERTopic Neutral')

=======================================================
 PIPELINE COMPLETE
=======================================================
  Silhouette BEFORE:   0.5229
  Silhouette AFTER:    0.3694  (weighted avg)
  Note: See chart for full before/after explanation.
=======================================================

Coherence scores (c_v):
  Pro AI           0.4106
  Against AI       0.5349
  Neutral          0.5680

Saved files:
  comments_final.csv              ← all results with labels
  comments_with_sentiment.csv     ← all 17,182 + sentiment scores
  evaluation_results.csv          ← silhouette + DBI + coherence
  comment_embeddings.npy          ← AraBERT vectors
  silhouette_comparison.html      ← before vs after bar chart
  pro_ai_clusters.html            ← Pro AI scatter
  against_ai_clusters.html        ← Against AI scatter
  neutral_clusters.html           ← Neutral scatter
  all_sentiments_overview.html    ← Combined overview
  bertopic_pro_ai.html            ← BERTopic Pro AI
  bertopic_against_ai.html        ← BERTopic Against AI
  bertopic_neutral.html           ← BERTopic Neutral

In [107]:
print('='*60)
print('REPORT NUMBERS')
print('='*60)
print(f'Raw comments:              {len(docs_raw):,}')
print(f'Clean comments:            {len(docs):,}')
print(f'Confident comments:        {n_total:,}')
print(f'Confidence threshold:      0.50')
print()
print(f'Sentiment distribution (confident):')
print(f'  Pro AI:                  {n_pro:,}  ({n_pro/n_total*100:.1f}%)')
print(f'  Against AI:              {n_against:,}  ({n_against/n_total*100:.1f}%)')
print(f'  Neutral:                 {n_neutral:,}  ({n_neutral/n_total*100:.1f}%)')
print()
print(f'Silhouette BEFORE (raw):           {sil_before:.4f}')
print(f'Silhouette BEFORE (clean):         {sil_clean_before:.4f}')
print(f'Silhouette AFTER  (weighted avg):  {sil_after_weighted:.4f}')
print(f'DBI BEFORE (raw):                  {dbi_before:.4f}')
print(f'DBI BEFORE (clean):                {dbi_clean_before:.4f}')
print(f'DBI Pro AI:                        {dbi_pro:.4f}')
print(f'DBI Against AI:                    {dbi_against:.4f}')
print(f'DBI Neutral:                       {dbi_neutral:.4f}')
print()
print(f'Coherence (c_v):')
for group, score in coherence_results.items():
    print(f'  {group:<15}  {score:.4f}')
print()
print(f'Sub-cluster sizes:')
for cid in range(3):
    print(f'  Pro AI sub-cluster {cid}:      {(df_pro["sub_cluster"]==cid).sum():,}')
for cid in range(3):
    print(f'  Against AI sub-cluster {cid}:  {(df_against["sub_cluster"]==cid).sum():,}')
for cid in range(3):
    print(f'  Neutral sub-cluster {cid}:     {(df_neutral["sub_cluster"]==cid).sum():,}')

============================================================
REPORT NUMBERS
============================================================
Raw comments:              21,611
Clean comments:            17,182
Confident comments:        9,841
Confidence threshold:      0.50

Sentiment distribution (confident):
  Pro AI:                  5,479  (55.7%)
  Against AI:              2,856  (29.0%)
  Neutral:                 1,506  (15.3%)

Silhouette BEFORE (raw):           0.5229
Silhouette BEFORE (clean):         0.4091
Silhouette AFTER  (weighted avg):  0.3694
DBI BEFORE (raw):                  0.6870
DBI BEFORE (clean):                0.9604
DBI Pro AI:                        1.1185
DBI Against AI:                    0.8712
DBI Neutral:                       0.9521

Coherence (c_v):
  Pro AI           0.4106
  Against AI       0.5349
  Neutral          0.5680

Sub-cluster sizes:
  Pro AI sub-cluster 0:      1,352
  Pro AI sub-cluster 1:      2,556
  Pro AI sub-cluster 2:      1,571
  Against AI sub-cluster 0:  1,408
  Against AI sub-cluster 1:  921
  Against AI sub-cluster 2:  527
  Neutral sub-cluster 0:     706
  Neutral sub-cluster 1:     125
  Neutral sub-cluster 2:     675

In [108]:
# Add topic_bertopic to final CSV
df_pro['sentiment']     = 'Pro AI'
df_against['sentiment'] = 'Against AI'
df_neutral['sentiment'] = 'Neutral'

df_all = pd.concat([df_pro, df_against, df_neutral], ignore_index=True)

df_all['sentiment_arabic'] = df_all['sentiment'].map({
    'Pro AI':     'مؤيد للذكاء الاصطناعي',
    'Against AI': 'ضد الذكاء الاصطناعي',
    'Neutral':    'محايد'
})

output_cols = [
    'video_url', 'author', 'votes', 'time', 'sort_type',
    'comment', 'text_normalized', 'text_no_stopwords', 'token_count',
    'sentiment_label', 'sentiment_arabic', 'sentiment_score',
    'score_pro_ai', 'score_against_ai', 'score_neutral',
    'sub_cluster', 'topic_bertopic',
    'umap_x', 'umap_y'
]

output_cols = [c for c in output_cols if c in df_all.columns]

df_all[output_cols].to_csv(
    '/kaggle/working/comments_final.csv',
    index=False, encoding='utf-8-sig'
)

print('Columns saved:')
for c in output_cols:
    print(f'  {c}')
print(f'\nTotal rows: {len(df_all):,}')
print('Saved: comments_final.csv')

Columns saved:
  video_url
  author
  votes
  time
  sort_type
  comment
  text_normalized
  text_no_stopwords
  token_count
  sentiment_label
  sentiment_arabic
  sentiment_score
  score_pro_ai
  score_against_ai
  score_neutral
  sub_cluster
  topic_bertopic
  umap_x
  umap_y

Total rows: 9,841
Saved: comments_final.csv